/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javaP */

#ifndef _Included_javaP
#define _Included_javaP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javaP
 * Method:    say
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javaP_say
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
